let user_name="Ayush";
let user_name1=new String("Ayush");
console.log(typeof user_name);
console.log(typeof user_name1);
let user="  aayush  ";
console.log(user.length)
console.log(user.toUpperCase());
console.log(user.toLowerCase());
console.log(user.charAt(2));
console.log(user.indexOf('y'));
let user1="  Ayu sh   ";
console.log(user.trim().length);
console.log(user.replace('a','b'));
console.log(user.includes('aa'));
let us="Ayush%Santosh%Bhosale";
console.log(us.split('%'));
let us1="Ayush$Santosh$Bhosale";
console.log(us1.substring(-4,5));
let us2="AYUSH";
console.log(us2.slice(0,3));
